#include<iostream>
#include<unistd.h>
using namespace std;
int main()
{
    for (int i = 0; i < 2; i++) {

        cout << "   _[]_" << endl;
        cout << "   |~~|" << endl;
        cout << "   |oq|" << endl;
        cout << "  (|<>|)" << endl;
        cout << "   \\--/" << endl;
        cout << "   _><_" << endl;
        cout << "  -\\. /-" << endl;
        cout << " / |. | \\" << endl;
        cout << "/  |. |  \\" << endl;
        cout << "   |__|" << endl;
        cout << "    ||" << endl;
        cout << "   _||_" << endl;
        cout << "   _[]_" << endl;
        cout << "   |~~|" << endl;
        cout << "   |oq|" << endl;
        cout << "  (|<>|)" << endl;
        cout << "   \\--/" << endl;
        cout << "   _><_" << endl;
        cout << " --\\. /--" << endl;
        cout << "/  |. |  \\" << endl;
        cout << "   |. |" << endl;
        cout << "   |__|" << endl;
        cout << "    ||" << endl;
        cout << "   _||_" << endl;
        cout << "   _[]_" << endl;
        cout << "   |~~|" << endl;
        cout << "   |oq|" << endl;
        cout << "  (|<>|)" << endl;
        cout << "   \\--/" << endl;
        cout << "   _><_" << endl;
        cout << "  -\\. /---" << endl;
        cout << " / |. |  " << endl;
        cout << "/  |. |" << endl;
        cout << "   |__|" << endl;
        cout << "    ||" << endl;
        cout << "   _||_" << endl;
        cout << "   _[]_" << endl;
        cout << "   |~~|" << endl;
        cout << "   |oq|" << endl;
        cout << "  (|<>|)" << endl;
        cout << "   \\--/    " << endl;
        cout << "   _><_  /" << endl;
        cout << " --\\. /--" << endl;
        cout << "/  |. |" << endl;
        cout << "   |. |" << endl;
        cout << "   |__|" << endl;
        cout << "    ||" << endl;
        cout << "   _||_" << endl;
        cout << "   _[]_" << endl;
        cout << "   |~~|" << endl;
        cout << "   |oq|" << endl;
        cout << "  (|<>|)" << endl;
        cout << "   \\--/  /" << endl;
        cout << "   _><_ /" << endl;
        cout << "  -\\. /-" << endl;
        cout << " / |. |" << endl;
        cout << "/  |. |" << endl;
        cout << "   |__|" << endl;
        cout << "    ||" << endl;
        cout << "   _||_" << endl;
        cout << "   _[]_" << endl;
        cout << "   |~~|" << endl;
        cout << "   |oq|" << endl;
        cout << "  (|<>|)" << endl;
        cout << "   \\--/  *" << endl;
        cout << "   _><_ /" << endl;
        cout << " --\\. /-" << endl;
        cout << "/  |. |" << endl;
        cout << "   |. |" << endl;
        cout << "   |__|" << endl;
        cout << "    ||" << endl;
        cout << "   _||_" << endl;
        cout << "   _[]_" << endl;
        cout << "   |~~|" << endl;
        cout << "   |oq|" << endl;
        cout << "  (|<>|)" << endl;
        cout << "   \\--/  /" << endl;
        cout << "   _><_ /" << endl;
        cout << "---\\. /-" << endl;
        cout << "   |. |" << endl;
        cout << "   |. |" << endl;
        cout << "   |__|" << endl;
        cout << "    ||" << endl;
        cout << "   _||_" << endl;
        cout << "   _[]_" << endl;
        cout << "   |~~|" << endl;
        cout << "   |oq|" << endl;
        cout << "  (|<>|)" << endl;
        cout << "   \\--/  *" << endl;
        cout << "\\  _><_ /" << endl;
        cout << " --\\. /-" << endl;
        cout << "   |. |" << endl;
        cout << "   |. |" << endl;
        cout << "   |__|" << endl;
        cout << "    ||" << endl;
        cout << "   _||_" << endl;
        cout << "   _[]_" << endl;
        cout << "   |~~|" << endl;
        cout << "   |oq|" << endl;
        cout << "  (|<>|)" << endl;
        cout << "\\  \\--/  /" << endl;
        cout << " \\ _><_ /" << endl;
        cout << "  -\\. /-" << endl;
        cout << "   |. |" << endl;
        cout << "   |. |" << endl;
        cout << "   |__|" << endl;
        cout << "    ||" << endl;
        cout << "   _||_" << endl;
        cout << "   _[]_" << endl;
        cout << "   |~~|" << endl;
        cout << "   |oq|" << endl;
        cout << "  (|<>|)" << endl;
        cout << "*  \\--/  *" << endl;
        cout << " \\ _><_ /" << endl;
        cout << "  -\\. /-" << endl;
        cout << "   |. |" << endl;
        cout << "   |. |" << endl;
        cout << "   |__|" << endl;
        cout << "    ||" << endl;
        cout << "   _||_" << endl;
        cout << "   _[]_" << endl;
        cout << "   |~~|" << endl;
        cout << "   |oq|" << endl;
        cout << "  (|<>|)" << endl;
        cout << "   \\--/" << endl;
        cout << "*  _><_  *" << endl;
        cout << " --\\. /--" << endl;
        cout << "   |. |" << endl;
        cout << "   |. |" << endl;
        cout << "   |__|" << endl;
        cout << "    ||" << endl;
        cout << "   _||_" << endl;
        cout << "   _[]_" << endl;
        cout << "   |~~|" << endl;
        cout << "   |oq|" << endl;
        cout << "  (|<>|)" << endl;
        cout << "   \\--/" << endl;
        cout << "   _><_" << endl;
        cout << "*--\\. /--*" << endl;
        cout << "   |. |  " << endl;
        cout << "   |. |" << endl;
        cout << "   |__|" << endl;
        cout << "    ||" << endl;
        cout << "   _||_" << endl;
        cout << "   _[]_" << endl;
        cout << "   |~~|" << endl;
        cout << "   |oq|" << endl;
        cout << "  (|<>|)" << endl;
        cout << "   \\--/" << endl;
        cout << "   _><_" << endl;
        cout << " --\\. /--" << endl;
        cout << "*  |. |  *" << endl;
        cout << "   |. |" << endl;
        cout << "   |__|" << endl;
        cout << "    ||" << endl;
        cout << "   _||_" << endl;
        cout << "   _[]_" << endl;
        cout << "   |~~|" << endl;
        cout << "   |oq|" << endl;
        cout << "  (|<>|)" << endl;
        cout << "   \\--/" << endl;
        cout << "   _><_" << endl;
        cout << "  -\\. /-" << endl;
        cout << " / |. | \\" << endl;
        cout << "*  |. |  *" << endl;
        cout << "   |__|" << endl;
        cout << "    ||" << endl;
        cout << "   _||_" << endl;


    }
    cout << "   _[]_" << endl;
    cout << "   |~~|" << endl;
    cout << "   |oq|" << endl;
    cout << "  (|<>|)" << endl;
    cout << "   \\--/" << endl;
    cout << "   _><_" << endl;
    cout << "  -\\. /-" << endl;
    cout << " / |. | \\" << endl;
    cout << "/  |. |  \\" << endl;
    cout << "   |__|" << endl;
    cout << "    ||" << endl;
    cout << "   _||_" << endl;
}