#include <iostream>
#include<unistd.h>

int main() {
	using namespace std;
	for (int i = 0; i < 2; i++) {
		cout << "   _[]_   " << endl;
		cout << "   |~~|   " << endl;
		cout << "   |oq|   " << endl;
		cout << "  (|<>|)  " << endl;
		cout << "   \\--/   " << endl;
		cout << "   _><_   " << endl;
		cout << "  -\\. /-  " << endl;
		cout << " / |. | \\ " << endl;
		cout << "/  |. |  \\" << endl;
		cout << "   |__|   " << endl;
		cout << "    ||    " << endl;
		cout << "   _||_   " << endl;


		//Sleep(1000);
		//system("cls");
		cout << "   _[]_   " << endl;
		cout << "   |~~|   " << endl;
		cout << "   |oq|   " << endl;
		cout << "  (|<>|)  " << endl;
		cout << "   \\--/   " << endl;
		cout << "   _><_   " << endl;
		cout << " --\\. /-- " << endl;
		cout << "/  |. |  \\" << endl;
		cout << "   |. |   " << endl;
		cout << "   |__|   " << endl;
		cout << "    ||    " << endl;
		cout << "   _||_   " << endl;
		////Sleep(1000);
		//system("cls");
		cout << "   _[]_   " << endl;
		cout << "   |~~|   " << endl;
		cout << "   |oq|   " << endl;
		cout << "  (|<>|)  " << endl;
		cout << "   \\--/   " << endl;
		cout << "   _><_   " << endl;
		cout << "  -\\. /---" << endl;
		cout << " / |. |  " << endl;
		cout << "/  |. |   " << endl;
		cout << "   |__|   " << endl;
		cout << "    ||    " << endl;
		cout << "   _||_   " << endl;
		//Sleep(1000);
		//system("cls");
		cout << "   _[]_   " << endl;
		cout << "   |~~|   " << endl;
		cout << "   |oq|   " << endl;
		cout << "  (|<>|)  " << endl;
		cout << "   \\--/   " << endl;
		cout << "   _><_  /" << endl;
		cout << " --\\. /-- " << endl;
		cout << "/  |. |   " << endl;
		cout << "   |. |   " << endl;
		cout << "   |__|   " << endl;
		cout << "    ||    " << endl;
		cout << "   _||_   " << endl;
		//Sleep(1000);
		//system("cls");
		cout << "   _[]_   " << endl;
		cout << "   |~~|   " << endl;
		cout << "   |oq|   " << endl;
		cout << "  (|<>|)  " << endl;
		cout << "   \\--/  /" << endl;
		cout << "   _><_ / " << endl;
		cout << "  -\\. /-  " << endl;
		cout << " / |. |   " << endl;
		cout << "/  |. |   " << endl;
		cout << "   |__|   " << endl;
		cout << "    ||    " << endl;
		cout << "   _||_   " << endl;
		//Sleep(1000);
		//system("cls");
		cout << "   _[]_   " << endl;
		cout << "   |~~|   " << endl;
		cout << "   |oq|   " << endl;
		cout << "  (|<>|)  " << endl;
		cout << "   \\--/  *" << endl;
		cout << "   _><_ / " << endl;
		cout << " --\\. /-  " << endl;
		cout << "/  |. |   " << endl;
		cout << "   |. |   " << endl;
		cout << "   |__|   " << endl;
		cout << "    ||    " << endl;
		cout << "   _||_   " << endl;
		//Sleep(1000);
		//system("cls");
		cout << "   _[]_   " << endl;
		cout << "   |~~|   " << endl;
		cout << "   |oq|   " << endl;
		cout << "  (|<>|)  " << endl;
		cout << "   \\--/  /" << endl;
		cout << "   _><_ / " << endl;
		cout << "---\\. /-  " << endl;
		cout << "   |. |   " << endl;
		cout << "   |. |   " << endl;
		cout << "   |__|   " << endl;
		cout << "    ||    " << endl;
		cout << "   _||_   " << endl;
		//Sleep(1000);
		//system("cls");
		cout << "   _[]_   " << endl;
		cout << "   |~~|   " << endl;
		cout << "   |oq|   " << endl;
		cout << "  (|<>|)  " << endl;
		cout << "   \\--/  *" << endl;
		cout << "\\  _><_ / " << endl;
		cout << " --\\. /-  " << endl;
		cout << "   |. |   " << endl;
		cout << "   |. |   " << endl;
		cout << "   |__|   " << endl;
		cout << "    ||    " << endl;
		cout << "   _||_   " << endl;
		//Sleep(1000);
		//system("cls");
		cout << "   _[]_   " << endl;
		cout << "   |~~|   " << endl;
		cout << "   |oq|   " << endl;
		cout << "  (|<>|)  " << endl;
		cout << "\\  \\--/  /" << endl;
		cout << " \\ _><_ / " << endl;
		cout << "  -\\. /-  " << endl;
		cout << "   |. |   " << endl;
		cout << "   |. |   " << endl;
		cout << "   |__|   " << endl;
		cout << "    ||    " << endl;
		cout << "   _||_   " << endl;
		//Sleep(1000);
		//system("cls");
		cout << "   _[]_   " << endl;
		cout << "   |~~|   " << endl;
		cout << "   |oq|   " << endl;
		cout << "  (|<>|)  " << endl;
		cout << "*  \\--/  *" << endl;
		cout << " \\ _><_ / " << endl;
		cout << "  -\\. /-  " << endl;
		cout << "   |. |   " << endl;
		cout << "   |. |   " << endl;
		cout << "   |__|   " << endl;
		cout << "    ||    " << endl;
		cout << "   _||_   " << endl;
		//Sleep(1000);
		//system("cls");
		cout << "   _[]_   " << endl;
		cout << "   |~~|   " << endl;
		cout << "   |oq|   " << endl;
		cout << "  (|<>|)  " << endl;
		cout << "   \\--/   " << endl;
		cout << " * _><_ * " << endl;
		cout << " --\\. /-- " << endl;
		cout << "   |. |   " << endl;
		cout << "   |. |   " << endl;
		cout << "   |__|   " << endl;
		cout << "    ||    " << endl;
		cout << "   _||_   " << endl;
		//Sleep(1000);
		//system("cls");
		cout << "   _[]_   " << endl;
		cout << "   |~~|   " << endl;
		cout << "   |oq|   " << endl;
		cout << "  (|<>|)  " << endl;
		cout << "   \\--/   " << endl;
		cout << "   _><_   " << endl;
		cout << "*--\\. /--*" << endl;
		cout << "   |. |   " << endl;
		cout << "   |. |   " << endl;
		cout << "   |__|   " << endl;
		cout << "    ||    " << endl;
		cout << "   _||_   " << endl;
		//Sleep(1000);
		//system("cls");
		cout << "   _[]_   " << endl;
		cout << "   |~~|   " << endl;
		cout << "   |oq|   " << endl;
		cout << "  (|<>|)  " << endl;
		cout << "   \\--/   " << endl;
		cout << "   _><_   " << endl;
		cout << " --\\. /-- " << endl;
		cout << "*  |. |  *" << endl;
		cout << "   |. |   " << endl;
		cout << "   |__|   " << endl;
		cout << "    ||    " << endl;
		cout << "   _||_   " << endl;
		//Sleep(1000);
		//system("cls");
		cout << "   _[]_   " << endl;
		cout << "   |~~|   " << endl;
		cout << "   |oq|   " << endl;
		cout << "  (|<>|)  " << endl;
		cout << "   \\--/   " << endl;
		cout << "   _><_   " << endl;
		cout << "  -\\. /-  " << endl;
		cout << " / |. | \\ " << endl;
		cout << "*  |. |  *" << endl;
		cout << "   |__|   " << endl;
		cout << "    ||    " << endl;
		cout << "   _||_   " << endl;
		//Sleep(1000);
		//system("cls");
		cout << "   _[]_   " << endl;
		cout << "   |~~|   " << endl;
		cout << "   |oq|   " << endl;
		cout << "  (|<>|)  " << endl;
		cout << "   \\--/   " << endl;
		cout << "   _><_   " << endl;
		cout << "  -\\. /-  " << endl;
		cout << " / |. | \\ " << endl;
		cout << "/  |. |  \\" << endl;
		cout << "   |__|   " << endl;
		cout << "    ||    " << endl;
		cout << "   _||_   " << endl;
		//Sleep(1000);
		//system("cls");



	}

}