#include <iostream>
#include <unistd.h>
using namespace std;

int main() {
	cout << "   _[]_   " << endl;
	cout << "   |~~|   " << endl;
	cout << "   |oq|   " << endl;
	cout << "  (|<>|)  " << endl;
	cout << "   \\__/   " << endl;
	cout << "   _><_   " << endl;
	cout << "  -\\. /-  " << endl;
	cout << " / |. | \\ " << endl;
	cout << "/  |. |  \\" << endl;
	cout << "   |__|   " << endl;
	cout << "    ||    " << endl;
	cout << "   _||_   " << endl;
	//Sleep(1000);
	//System("cls");
	cout << "   _[]_   " << endl;
	cout << "   |~~|   " << endl;
	cout << "   |oq|   " << endl;
	cout << "  (|<>|)  " << endl;
	cout << "   \\__/   " << endl;
	cout << "   _><_   " << endl;
	cout << " --\\. /--  " << endl;
	cout << "/  |. |  \\" << endl;
	cout << "   |. |   " << endl;
	cout << "   |__|   " << endl;
	cout << "    ||    " << endl;
	cout << "   _||_   " << endl;
	//Sleep(1000);
	//System("cls");
	cout << "   _[]_   " << endl;
	cout << "   |~~|   " << endl;
	cout << "   |oq|   " << endl;
	cout << "  (|<>|)  " << endl;
	cout << "   \\__/   " << endl;
	cout << "   _><_   " << endl;
	cout << "  -\\. /---" << endl;
	cout << " / |. |   " << endl;
	cout << "/  |. |   " << endl;
	cout << "   |__|   " << endl;
	cout << "    ||    " << endl;
	cout << "   _||_   " << endl;
	//Sleep(1000);
	//System("cls");
	cout << "   _[]_   " << endl;
	cout << "   |~~|   " << endl;
	cout << "   |oq|   " << endl;
	cout << "  (|<>|)  " << endl;
	cout << "   \\__/   " << endl;
	cout << "   _><_  /" << endl;
	cout << " --\\. /-- " << endl;
	cout << "/  |. |   " << endl;
	cout << "   |. |   " << endl;
	cout << "   |__|   " << endl;
	cout << "    ||    " << endl;
	cout << "   _||_   " << endl;
	//Sleep(1000  );
	//System("cls");
	cout << "   _[]_   " << endl;
	cout << "   |~~|   " << endl;
	cout << "   |oq|   " << endl;
	cout << "  (|<>|)  " << endl;
	cout << "   \\__/  /" << endl;
	cout << "   _><_ / " << endl;
	cout << "  -\\. /-  " << endl;
	cout << " / |. |   " << endl;
	cout << "/  |. |   " << endl;
	cout << "   |__|   " << endl;
	cout << "    ||    " << endl;
	cout << "   _||_   " << endl;
	//Sleep(1000  );
	//System("cls");
	cout << "   _[]_   " << endl;
	cout << "   |~~|   " << endl;
	cout << "   |oq|   " << endl;
	cout << "  (|<>|)  " << endl;
	cout << "   \\__/  *" << endl;
	cout << "   _><_ / " << endl;
	cout << " --\\. /-  " << endl;
	cout << "/  |. |   " << endl;
	cout << "   |. |   " << endl;
	cout << "   |__|   " << endl;
	cout << "    ||    " << endl;
	cout << "   _||_   " << endl;
	//Sleep(1000  );
	//System("cls");
	cout << "   _[]_   " << endl;
	cout << "   |~~|   " << endl;
	cout << "   |oq|   " << endl;
	cout << "  (|<>|)  " << endl;
	cout << "   \\__/  /" << endl;
	cout << "   _><_ / " << endl;
	cout << "---\\. /-  " << endl;
	cout << "   |. |   " << endl;
	cout << "   |. |   " << endl;
	cout << "   |__|   " << endl;
	cout << "    ||    " << endl;
	cout << "   _||_   " << endl;
	//Sleep(1000  );
	//System("cls");
	cout << "   _[]_   " << endl;
	cout << "   |~~|   " << endl;
	cout << "   |oq|   " << endl;
	cout << "  (|<>|)  " << endl;
	cout << "   \\__/  *" << endl;
	cout << "\\  _><_ / " << endl;
	cout << " --\\. /-  " << endl;
	cout << "   |. |   " << endl;
	cout << "   |. |   " << endl;
	cout << "   |__|   " << endl;
	cout << "    ||    " << endl;
	cout << "   _||_   " << endl;
	//Sleep(1000  );
	//System("cls");
	cout << "   _[]_   " << endl;
	cout << "   |~~|   " << endl;
	cout << "   |oq|   " << endl;
	cout << "  (|<>|)  " << endl;
	cout << "\\  \\__/  /" << endl;
	cout << " \\ _><_ / " << endl;
	cout << "  -\\. /-  " << endl;
	cout << "   |. |   " << endl;
	cout << "   |. |   " << endl;
	cout << "   |__|   " << endl;
	cout << "    ||    " << endl;
	cout << "   _||_   " << endl;
	//Sleep(1000  );
	//System("cls");
	cout << "   _[]_   " << endl;
	cout << "   |~~|   " << endl;
	cout << "   |oq|   " << endl;
	cout << "  (|<>|)  " << endl;
	cout << "*  \\__/  *" << endl;
	cout << " \\ _><_ / " << endl;
	cout << "  -\\. /-  " << endl;
	cout << "   |. |   " << endl;
	cout << "   |. |   " << endl;
	cout << "   |__|   " << endl;
	cout << "    ||    " << endl;
	cout << "   _||_   " << endl;
	//Sleep(1000  );
	//System("cls");
	cout << "   _[]_   " << endl;
	cout << "   |~~|   " << endl;
	cout << "   |oq|   " << endl;
	cout << "  (|<>|)  " << endl;
	cout << "   \\__/   " << endl;
	cout << "*  _><_  *" << endl;
	cout << " --\\. /-- " << endl;
	cout << "   |. |   " << endl;
	cout << "   |. |   " << endl;
	cout << "   |__|   " << endl;
	cout << "    ||    " << endl;
	cout << "   _||_   " << endl;
	//Sleep(1000  );
	//System("cls");
	cout << "   _[]_   " << endl;
	cout << "   |~~|   " << endl;
	cout << "   |oq|   " << endl;
	cout << "  (|<>|)  " << endl;
	cout << "   \\__/   " << endl;
	cout << "   _><_   " << endl;
	cout << "*--\\. /--*" << endl;
	cout << "   |. |   " << endl;
	cout << "   |. |   " << endl;
	cout << "   |__|   " << endl;
	cout << "    ||    " << endl;
	cout << "   _||_   " << endl;
	//Sleep(1000  );
	//System("cls");
	cout << "   _[]_   " << endl;
	cout << "   |~~|   " << endl;
	cout << "   |oq|   " << endl;
	cout << "  (|<>|)  " << endl;
	cout << "   \\__/   " << endl;
	cout << "   _><_   " << endl;
	cout << " --\\. /-- " << endl;
	cout << "*  |. |  *" << endl;
	cout << "   |. |   " << endl;
	cout << "   |__|   " << endl;
	cout << "    ||    " << endl;
	cout << "   _||_   " << endl;
	//Sleep(1000  );
	//System("cls");
	cout << "   _[]_   " << endl;
	cout << "   |~~|   " << endl;
	cout << "   |oq|   " << endl;
	cout << "  (|<>|)  " << endl;
	cout << "   \\__/   " << endl;
	cout << "   _><_   " << endl;
	cout << "  -\\. /-  " << endl;
	cout << " / |. | \\ " << endl;
	cout << "*  |. |  *" << endl;
	cout << "   |__|   " << endl;
	cout << "    ||    " << endl;
	cout << "   _||_   " << endl;
	//Sleep(1000  );
	//System("cls");
	cout << "   _[]_   " << endl;
	cout << "   |~~|   " << endl;
	cout << "   |oq|   " << endl;
	cout << "  (|<>|)  " << endl;
	cout << "   \\__/   " << endl;
	cout << "   _><_   " << endl;
	cout << "  -\\. /-  " << endl;
	cout << " / |. | \\ " << endl;
	cout << "/  |. |  \\" << endl;
	cout << "   |__|   " << endl;
	cout << "    ||    " << endl;
	cout << "   _||_   " << endl;
	//Sleep(1000  );
	//System("cls");
	cout << "   _[]_   " << endl;
	cout << "   |~~|   " << endl;
	cout << "   |oq|   " << endl;
	cout << "  (|<>|)  " << endl;
	cout << "   \\__/   " << endl;
	cout << "   _><_   " << endl;
	cout << " --\\. /-- " << endl;
	cout << "/  |. |  \\" << endl;
	cout << "   |. |   " << endl;
	cout << "   |__|   " << endl;
	cout << "    ||    " << endl;
	cout << "   _||_   " << endl;
	//Sleep(1000);
	//System("cls");
	cout << "   _[]_   " << endl;
	cout << "   |~~|   " << endl;
	cout << "   |oq|   " << endl;
	cout << "  (|<>|)  " << endl;
	cout << "   \\__/   " << endl;
	cout << "   _><_   " << endl;
	cout << "  -\\. /---" << endl;
	cout << " / |. |   " << endl;
	cout << "/  |. |   " << endl;
	cout << "   |__|   " << endl;
	cout << "    ||    " << endl;
	cout << "   _||_   " << endl;
	//Sleep(1000);
	//System("cls");
	cout << "   _[]_   " << endl;
	cout << "   |~~|   " << endl;
	cout << "   |oq|   " << endl;
	cout << "  (|<>|)  " << endl;
	cout << "   \\__/   " << endl;
	cout << "   _><_  /" << endl;
	cout << " --\\. /-- " << endl;
	cout << "/  |. |   " << endl;
	cout << "   |. |   " << endl;
	cout << "   |__|   " << endl;
	cout << "    ||    " << endl;
	cout << "   _||_   " << endl;
	//Sleep(1000);
	//System("cls");
	cout << "   _[]_   " << endl;
	cout << "   |~~|   " << endl;
	cout << "   |oq|   " << endl;
	cout << "  (|<>|)  " << endl;
	cout << "   \\__/  /" << endl;
	cout << "   _><_ / " << endl;
	cout << "  -\\. /-  " << endl;
	cout << " / |. |   " << endl;
	cout << "/  |. |   " << endl;
	cout << "   |__|   " << endl;
	cout << "    ||    " << endl;
	cout << "   _||_   " << endl;
	//Sleep(1000);
	//System("cls");
	cout << "   _[]_   " << endl;
	cout << "   |~~|   " << endl;
	cout << "   |oq|   " << endl;
	cout << "  (|<>|)  " << endl;
	cout << "   \\__/  *" << endl;
	cout << "   _><_ / " << endl;
	cout << " --\\. /-  " << endl;
	cout << "/  |. |   " << endl;
	cout << "   |. |   " << endl;
	cout << "   |__|   " << endl;
	cout << "    ||    " << endl;
	cout << "   _||_   " << endl;
	//Sleep(1000);
	//System("cls");
	cout << "   _[]_   " << endl;
	cout << "   |~~|   " << endl;
	cout << "   |oq|   " << endl;
	cout << "  (|<>|)  " << endl;
	cout << "   \\__/  /" << endl;
	cout << "   _><_ / " << endl;
	cout << "---\\. /-  " << endl;
	cout << "   |. |   " << endl;
	cout << "   |. |   " << endl;
	cout << "   |__|   " << endl;
	cout << "    ||    " << endl;
	cout << "   _||_   " << endl;
	//Sleep(1000);
	//System("cls");
	cout << "   _[]_   " << endl;
	cout << "   |~~|   " << endl;
	cout << "   |oq|   " << endl;
	cout << "  (|<>|)  " << endl;
	cout << "   \\__/  *" << endl;
	cout << "\\  _><_ / " << endl;
	cout << " --\\. /-  " << endl;
	cout << "   |. |   " << endl;
	cout << "   |. |   " << endl;
	cout << "   |__|   " << endl;
	cout << "    ||    " << endl;
	cout << "   _||_   " << endl;
	//Sleep(1000);
	//System("cls");
	cout << "   _[]_   " << endl;
	cout << "   |~~|   " << endl;
	cout << "   |oq|   " << endl;
	cout << "  (|<>|)  " << endl;
	cout << "\\  \\__/  /" << endl;
	cout << " \\ _><_ / " << endl;
	cout << "  -\\. /-  " << endl;
	cout << "   |. |   " << endl;
	cout << "   |. |   " << endl;
	cout << "   |__|   " << endl;
	cout << "    ||    " << endl;
	cout << "   _||_   " << endl;
	//Sleep(1000);
	//System("cls");
	cout << "   _[]_   " << endl;
	cout << "   |~~|   " << endl;
	cout << "   |oq|   " << endl;
	cout << "  (|<>|)  " << endl;
	cout << "*  \\__/  *" << endl;
	cout << " \\ _><_ / " << endl;
	cout << "  -\\. /-  " << endl;
	cout << "   |. |   " << endl;
	cout << "   |. |   " << endl;
	cout << "   |__|   " << endl;
	cout << "    ||    " << endl;
	cout << "   _||_   " << endl;
	//Sleep(1000);
	//System("cls");
	cout << "   _[]_   " << endl;
	cout << "   |~~|   " << endl;
	cout << "   |oq|   " << endl;
	cout << "  (|<>|)  " << endl;
	cout << "   \\__/   " << endl;
	cout << "*  _><_  *" << endl;
	cout << " --\\. /-- " << endl;
	cout << "   |. |   " << endl;
	cout << "   |. |   " << endl;
	cout << "   |__|   " << endl;
	cout << "    ||    " << endl;
	cout << "   _||_   " << endl;
	//Sleep(1000);
	//System("cls");
	cout << "   _[]_   " << endl;
	cout << "   |~~|   " << endl;
	cout << "   |oq|   " << endl;
	cout << "  (|<>|)  " << endl;
	cout << "   \\__/   " << endl;
	cout << "   _><_   " << endl;
	cout << "*--\\. /--*" << endl;
	cout << "   |. |   " << endl;
	cout << "   |. |   " << endl;
	cout << "   |__|   " << endl;
	cout << "    ||    " << endl;
	cout << "   _||_   " << endl;
	//Sleep(1000);
	//System("cls");
	cout << "   _[]_   " << endl;
	cout << "   |~~|   " << endl;
	cout << "   |oq|   " << endl;
	cout << "  (|<>|)  " << endl;
	cout << "   \\__/   " << endl;
	cout << "   _><_   " << endl;
	cout << " --\\. /-- " << endl;
	cout << "*  |. |  *" << endl;
	cout << "   |. |   " << endl;
	cout << "   |__|   " << endl;
	cout << "    ||    " << endl;
	cout << "   _||_   " << endl;
	//Sleep(1000);
	//System("cls");
	cout << "   _[]_   " << endl;
	cout << "   |~~|   " << endl;
	cout << "   |oq|   " << endl;
	cout << "  (|<>|)  " << endl;
	cout << "   \\__/   " << endl;
	cout << "   _><_   " << endl;
	cout << "  -\\. /-  " << endl;
	cout << " / |. | \\ " << endl;
	cout << "*  |. |  *" << endl;
	cout << "   |__|   " << endl;
	cout << "    ||    " << endl;
	cout << "   _||_   " << endl;
	//Sleep(1000);
	//System("cls");
	cout << "   _[]_   " << endl;
	cout << "   |~~|   " << endl;
	cout << "   |oq|   " << endl;
	cout << "  (|<>|)  " << endl;
	cout << "   \\__/   " << endl;
	cout << "   _><_   " << endl;
	cout << "  -\\. /-  " << endl;
	cout << " / |. | \\ " << endl;
	cout << "/  |. |  \\" << endl;
	cout << "   |__|   " << endl;
	cout << "    ||    " << endl;
	cout << "   _||_   " << endl;
}